version: '3'

services:
  axon-server:
    image: axoniq/axonserver
    ports:
      - 8024:8024
      - 8124:8124
    environment:
      - AXONSERVER_HOSTNAME=localhost
    hostname: localhost
    container_name: boris-axon-server
    restart: always